itzg/mc-image-helper

src/main/java/me/itzg/helpers/get/ExtendedRequestRetryStrategy.java, src/main/java/me/itzg/helpers/get/GetCommand.java, src/test/java/me/itzg/helpers/get/GetCommandTest.java
=> feat(get): added retry configuration and handles 403's

src/main/java/me/itzg/helpers/get/GetCommand.java, src/main/java/me/itzg/helpers/get/JsonPathOutputHandler.java, src/test/java/me/itzg/helpers/get/GetCommandTest.java
For https://github.com/itzg/docker-minecraft-server/issues/1323
=> feat(get): configurable behavior when json path is missing

build.gradle, src/main/java/me/itzg/helpers/McImageHelper.java, src/main/java/me/itzg/helpers/http/ReactorNettyBits.java, src/main/java/me/itzg/helpers/http/Uris.java, src/main/java/me/itzg/helpers/json/ObjectMappers.java, src/main/java/me/itzg/helpers/modrinth/HttpClientException.java, src/main/java/me/itzg/helpers/modrinth/Loader.java, src/main/java/me/itzg/helpers/modrinth/Manifest.java, src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java, src/main/java/me/itzg/helpers/modrinth/model/DependencyType.java, src/main/java/me/itzg/helpers/modrinth/model/Project.java, src/main/java/me/itzg/helpers/modrinth/model/ProjectType.java, src/main/java/me/itzg/helpers/modrinth/model/ServerSide.java, src/main/java/me/itzg/helpers/modrinth/model/Version.java, src/main/java/me/itzg/helpers/modrinth/model/VersionDependency.java, src/main/java/me/itzg/helpers/modrinth/model/VersionFile.java, src/main/java/me/itzg/helpers/modrinth/model/VersionType.java
Such as
```
mc-image-helper modrinth \
--projects fallingtree --loader fabric --game-version 1.19 --download-optional-dependencies
```
=> modrinth: Initial support to download modrinth project files

src/main/java/me/itzg/helpers/get/GetCommand.java, src/main/java/me/itzg/helpers/http/LenientUriConverter.java, src/test/java/me/itzg/helpers/http/LenientUriConverterTest.java
=> Avoid re-encoding URI

src/main/java/me/itzg/helpers/forge/ForgeInstaller.java, src/main/java/me/itzg/helpers/forge/InstallForgeCommand.java, src/main/java/me/itzg/helpers/http/FetchBuilder.java
=> fix(install-forge): forge-version wasn't validated correctly

build.gradle, src/main/java/me/itzg/helpers/McImageHelper.java, src/main/java/me/itzg/helpers/http/FetchBuilder.java, src/main/java/me/itzg/helpers/http/ObjectFetchBuilder.java, src/main/java/me/itzg/helpers/http/ObjectMapperHandler.java, src/main/java/me/itzg/helpers/http/SpecificFileFetchBuilder.java, src/main/java/me/itzg/helpers/mvn/MavenDownloadCommand.java, src/main/java/me/itzg/helpers/mvn/MavenMetadata.java
Supports https://github.com/itzg/docker-minecraft-server/issues/1678#issuecomment-1233649801
=> feat: added maven-download command

src/main/java/me/itzg/helpers/fabric/InstallFabricLoaderCommand.java, src/main/java/me/itzg/helpers/http/FailedRequestException.java, src/main/java/me/itzg/helpers/http/FetchBuilderBase.java
Also
- better error reporting of failed HTTP request
=> fabric: allow LATEST for installer/loader version

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
=> curseforge: exclude client mods

src/main/java/me/itzg/helpers/forge/ForgeInstaller.java, src/main/java/me/itzg/helpers/http/FailedRequestException.java
Capture the correct exception, extend it with a status code and add support for the odd mc172 versions
=> Fixed older Forge installers

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/model/ManifestFileRef.java
Correct way to implement vs https://github.com/itzg/mc-image-helper/pull/87
=> curseforge: include only server mods

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/model/ManifestFileRef.java, src/test/java/me/itzg/helpers/curseforge/CurseForgeInstallerTest.java
=> curseforge: exclude client mods but include libraries

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeManifest.java, src/main/java/me/itzg/helpers/curseforge/ModPackResults.java, src/main/java/me/itzg/helpers/files/Manifests.java, src/main/java/me/itzg/helpers/forge/ForgeInstaller.java, src/main/java/me/itzg/helpers/forge/ForgeManifest.java, src/main/java/me/itzg/helpers/forge/LegacyManifest.java
Also
- use new manifest type for Forge
Resolves #105 
Resolves #79
=> curseforge: ensure mod loader is sync'ed with existing modpack

src/main/java/me/itzg/helpers/errors/ExceptionHandler.java, src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
For https://github.com/itzg/docker-minecraft-server/issues/1908
=> forge: fixed a regression when installing given file in working dir

src/main/java/me/itzg/helpers/http/FailedRequestException.java, src/main/java/me/itzg/helpers/http/SpecificFileFetchBuilder.java
Fixes regression introduced by #94 and broke #88
Should resolve https://github.com/itzg/docker-minecraft-server/issues/1916
=> http: restore bad response status handling in file fetch

src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java, src/main/java/me/itzg/helpers/files/IoStreams.java, src/main/java/me/itzg/helpers/http/FailedRequestException.java
For https://github.com/itzg/docker-minecraft-server/issues/1941
=> fabric: add support for older mc+launcher versions

src/main/java/me/itzg/helpers/http/SharedFetchArgs.java
For https://github.com/itzg/docker-minecraft-server/issues/1965#issuecomment-1433894290
=> http: longer default for response timeout

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeManifest.java
For https://github.com/itzg/docker-minecraft-server/issues/1975
=> curseforge: include modpack filename in manifest

src/main/java/me/itzg/helpers/modrinth/Loader.java, src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
=> modrinth: expand loaders allowed to paper and purpur

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
Because of https://github.com/modrinth/labrinth/issues/559
Helps with https://github.com/itzg/docker-minecraft-server/issues/1973#issuecomment-1455151499
=> modrinth: assume first version file when none are primary

src/main/java/me/itzg/helpers/McImageHelper.java, src/main/java/me/itzg/helpers/get/GetCommand.java
Added to help debug https://github.com/itzg/docker-minecraft-server/issues/2001
=> Allow for trace logging Apache HttpClient activity

src/main/java/me/itzg/helpers/files/IoStreams.java, src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
Helps https://github.com/itzg/docker-minecraft-server/issues/2011
=> forge: extract version from provided installer file

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
Reported in https://github.com/itzg/docker-minecraft-server/pull/2022
=> autocf: fixed issue with exclude file alone was ignored

src/main/java/me/itzg/helpers/http/SharedFetchArgs.java
Noted [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1088202720533565512)
=> http: bump default FETCH_RESPONSE_TIMEOUT to 30S

src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
Also for #174 
Addresses https://github.com/itzg/mc-image-helper/pull/176#discussion_r1148397469
=> forge: support 1.5.x install_profile.json

src/main/java/me/itzg/helpers/http/FilenameExtractor.java
For https://github.com/itzg/docker-minecraft-server/issues/2044
=> http: allow for RFC 2047 encoded content disposition filenames

src/main/java/me/itzg/helpers/http/SharedFetch.java, src/main/java/me/itzg/helpers/http/SharedFetchArgs.java
Observed [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1092994433152192524)
=> http: allow connection pool max idle timeout config

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
Discussed [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1094347501135466656)
=> cf: include VERSION in results file

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
in addition to https://github.com/itzg/mc-image-helper/pull/193
=> cf: include VERSION in results file also with existing install

src/main/java/me/itzg/helpers/curseforge/CategoryInfo.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
Also refactored out CurseForgeApiClient
=> cf: support installation given modpack manifest file

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
=> cf: don't use extra parallelism with modpack content

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
Addresses https://github.com/itzg/docker-minecraft-server/issues/2091
=> modrinth: ensure non-required dependency doesn't mask explicit project request

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
For https://github.com/itzg/docker-minecraft-server/issues/2067
=> cf: added support for using a downloads repo

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
=> modrinth: provide clearer error when modrinth project doesn't exist

README.md, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ProjectRef.java
See https://github.com/itzg/docker-minecraft-server/actions/runs/4972702240/jobs/8898065201?pr=2128
=> modrinth: fixed issue when modrinth project not qualified by version id/type

src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java, src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
=> modrinth: fail when a requested project is not available for loader+game version

src/main/java/me/itzg/helpers/http/OutputToDirectoryFetchBuilder.java
For https://github.com/itzg/docker-minecraft-server/issues/2232
=> fetch: correctly handle NOT_MODIFIED status when output to directory

src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java, src/main/java/me/itzg/helpers/fabric/InstallFabricLoaderCommand.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1120030756656386088)
=> fabric: make sure to re-write results file

src/main/java/me/itzg/helpers/vanillatweaks/VanillaTweaksCommand.java
=> vt: validate pack definition has a type

src/main/java/me/itzg/helpers/http/Uris.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java, src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java, src/main/java/me/itzg/helpers/modrinth/ResolvedProject.java
For https://github.com/itzg/docker-minecraft-server/issues/2140
=> modrinth: bulk retrieve initial list of projects

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/ModPackResults.java, src/main/java/me/itzg/helpers/curseforge/PathWithInfo.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1122679576422797312)
=> cf: write out "needs download" file

.devcontainer/devcontainer.json, build.gradle
Reported in https://github.com/itzg/docker-minecraft-server/issues/2275
=> http: use CXF library for Java 8

src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java
=> modrinth: allow for optional modpack env designation

src/test/java/me/itzg/helpers/find/FindCommandTest.java
Confirming for https://github.com/itzg/docker-minecraft-server/issues/2316
=> find: add unit test for delete with excludes

src/main/java/me/itzg/helpers/find/FindCommand.java, src/main/java/me/itzg/helpers/find/FindFilesVisitor.java, src/main/java/me/itzg/helpers/find/MatchHandler.java, src/main/java/me/itzg/helpers/find/TrackShallowest.java, src/test/java/me/itzg/helpers/find/FindCommandTest.java
Follow up to https://github.com/itzg/docker-minecraft-server/issues/2316
=> find: remove directories emptied by file removals

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeFilesCommand.java
=> cf-files: API key not required for full cleanup

src/main/java/me/itzg/helpers/mvn/MavenDownloadCommand.java, src/main/java/me/itzg/helpers/mvn/MavenRepoApi.java, src/test/java/me/itzg/helpers/mvn/MavenRepoApiTest.java, src/test/resources/mvn/__files/packwiz_maven-metadata.xml
=> mvn: cache metadata retrieval

src/main/java/me/itzg/helpers/files/IoStreams.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java
=> modrinth: resolve "only DEFLATED entries can have EXT"

src/main/java/me/itzg/helpers/users/ManageUsersCommand.java, src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2345
=> users: allow for copying over existing ops/whitelist file

src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiPackFetcher.java, src/main/java/me/itzg/helpers/modrinth/ResolvedProject.java, src/test/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommandTest.java, src/test/java/me/itzg/helpers/modrinth/ModrinthTestHelpers.java
For https://github.com/itzg/docker-minecraft-server/issues/2344
=> modrinth: ensure requested loader for modpack is optional

src/main/java/me/itzg/helpers/users/ManageUsersCommand.java, src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java, src/test/resources/ModrinthCommandTest/__files/NOTES.md
For https://github.com/itzg/docker-minecraft-server/issues/2351
=> users: trim whitespace from whitelist/ops inputs

src/main/java/me/itzg/helpers/files/Manifests.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiPackFetcher.java, src/test/java/me/itzg/helpers/modrinth/ModrinthApiPackFetcherTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2344
=> modrinth: option to ignore missing files from modpack update check

.github/dependabot.yml, src/main/java/me/itzg/helpers/McImageHelper.java, src/main/java/me/itzg/helpers/properties/PropertyDefinition.java, src/main/java/me/itzg/helpers/properties/SetPropertiesCommand.java, src/test/java/me/itzg/helpers/env/MappedEnvVarProvider.java, src/test/java/me/itzg/helpers/properties/SetPropertiesCommandTest.java, src/test/resources/properties/property-definitions.json, src/test/resources/properties/server.properties
=> Add a set-properties sub-command

dev/modrinth.http, src/main/java/me/itzg/helpers/modrinth/Loader.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java, src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java, src/test/java/me/itzg/helpers/modrinth/ModrinthApiClientTest.java, src/test/resources/__files/modrinth/project-BITzwT7B-version-resp.json
For https://github.com/itzg/docker-minecraft-server/issues/2187
=> modrinth: support plugin lookups that are compatible with selected loader

dev/modrinth.http, src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java, src/main/java/me/itzg/helpers/paper/PaperDownloadsClient.java, src/test/java/me/itzg/helpers/modrinth/ModrinthCommandTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2356
=> modrinth: provide option to not download dependencies

src/main/java/me/itzg/helpers/versions/JavaReleaseCommand.java
=> java-release: support >= 21

dev/curseforge.http, dev/modrinth.http, src/main/java/me/itzg/helpers/McImageHelper.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/files/ReactiveFileUtils.java, src/main/java/me/itzg/helpers/forge/ForgeInstaller.java, src/main/java/me/itzg/helpers/forge/ForgeInstallerResolver.java, src/main/java/me/itzg/helpers/forge/InstallForgeCommand.java, src/main/java/me/itzg/helpers/forge/InstallNeoForgeCommand.java, src/main/java/me/itzg/helpers/forge/InstallerResolver.java, src/main/java/me/itzg/helpers/forge/NeoForgeInstallerResolver.java, src/main/java/me/itzg/helpers/forge/PromoEntry.java, src/main/java/me/itzg/helpers/forge/ProvidedInstallerResolver.java, src/main/java/me/itzg/helpers/forge/ResolvedVersions.java, src/main/java/me/itzg/helpers/forge/VersionPair.java, src/main/java/me/itzg/helpers/http/SpecificFileFetchBuilder.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java, src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java, src/test/java/me/itzg/helpers/modrinth/ModrinthPackInstallerTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2362
=> Added install-neoforge command

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/model/FileStatus.java
For https://github.com/itzg/docker-minecraft-server/issues/2403
=> cf: register checkpoint for each modpack file processed

src/main/java/me/itzg/helpers/properties/SetPropertiesCommand.java, src/test/java/me/itzg/helpers/properties/SetPropertiesCommandTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2407
=> props: allow for custom properties

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java, src/main/java/me/itzg/helpers/curseforge/OverridesApplier.java, src/main/java/me/itzg/helpers/curseforge/OverridesFromZipApplier.java, src/main/java/me/itzg/helpers/files/AntPathMatcher.java, src/test/java/me/itzg/helpers/files/AntPathMatcherTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2294
=> auto-cf: add option to exclude files from overrides

src/main/java/me/itzg/helpers/files/Manifests.java, src/test/java/me/itzg/helpers/files/ManifestsTest.java
=> Gracefully handle corrupted manifest files

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java, src/test/java/me/itzg/helpers/curseforge/CurseForgeApiClientTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2477
=> cf: trim API key

src/main/java/me/itzg/helpers/properties/SetPropertiesCommand.java, src/test/java/me/itzg/helpers/properties/SetPropertiesCommandTest.java, src/test/resources/properties/property-definitions.json
For https://github.com/itzg/docker-minecraft-server/issues/2478
=> props: add option to escape unicode

src/main/java/me/itzg/helpers/properties/SetPropertiesCommand.java, src/test/java/me/itzg/helpers/properties/SetPropertiesCommandTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2482
=> props: support pre-escaped unicode

src/main/java/me/itzg/helpers/users/ManageUsersCommand.java, src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2481
=> users: remove check for offline mode

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/env/SimplePlaceholders.java, src/main/java/me/itzg/helpers/files/ResultsFileWriter.java, src/main/java/me/itzg/helpers/forge/ForgeInstaller.java, src/main/java/me/itzg/helpers/modrinth/FetchedPack.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiPackFetcher.java, src/main/java/me/itzg/helpers/modrinth/ModrinthHttpPackFetcher.java, src/main/java/me/itzg/helpers/properties/SetPropertiesCommand.java, src/test/java/me/itzg/helpers/properties/SetPropertiesCommandTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2474
=> props: support placeholders in server properties

src/main/java/me/itzg/helpers/files/ReactiveFileUtils.java, src/main/java/me/itzg/helpers/http/OutputToDirectoryFetchBuilder.java, src/main/java/me/itzg/helpers/http/SpecificFileFetchBuilder.java
For https://github.com/itzg/docker-minecraft-server/issues/2491
=> http: stream file downloads to avoid 2GB limit

src/main/java/me/itzg/helpers/patch/PatchSetProcessor.java, src/main/java/me/itzg/helpers/patch/model/PatchDefinition.java, src/test/java/me/itzg/helpers/patch/PatchSetProcessorTest.java
=> patch: interpolate patch definition file name

README.md, build.gradle, src/main/java/me/itzg/helpers/patch/FileFormat.java, src/main/java/me/itzg/helpers/patch/Json5FileFormat.java, src/main/java/me/itzg/helpers/patch/JsonFileFormat.java, src/main/java/me/itzg/helpers/patch/ObjectMapperFileFormat.java, src/main/java/me/itzg/helpers/patch/PatchSetProcessor.java, src/main/java/me/itzg/helpers/patch/TomlFileFormat.java, src/main/java/me/itzg/helpers/patch/YamlFileFormat.java, src/test/java/me/itzg/helpers/patch/PatchSetProcessorTest.java, src/test/resources/patch/expected-setInToml.toml, src/test/resources/patch/testing.toml
=> patch: support TOML file processing

src/main/java/me/itzg/helpers/modrinth/ModrinthApiPackFetcher.java, src/test/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommandTest.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1180003259956596747)
=> modrinth: report error when no matching modpack version is available

build.gradle, src/test/java/me/itzg/helpers/get/GetCommandTest.java
See https://issues.apache.org/jira/browse/HTTPCLIENT-2307
=> build: downgrade httpclient5 due to buggy release 5.2.2

src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java, src/test/java/me/itzg/helpers/modrinth/ModrinthPackInstallerTest.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1180634934243758110)
=> modrinth: support excluding mods from modpack

src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
For https://github.com/itzg/docker-minecraft-server/issues/2523
=> cf: allow download page to be provided as page URL

src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
For https://github.com/itzg/docker-minecraft-server/issues/2541
=> forge: locate shim jar as entrypoint

src/main/java/me/itzg/helpers/modrinth/FilePackFetcher.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ProjectRef.java, src/test/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommandTest.java, src/test/java/me/itzg/helpers/modrinth/ProjectRefTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2144
=> modrinth: support local modpack files

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java, src/main/java/me/itzg/helpers/curseforge/MissingModsException.java, src/main/java/me/itzg/helpers/files/TabularOutput.java, src/test/java/me/itzg/helpers/files/TabularOutputTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2450
=> cf: allow for browser named files in final output

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java, src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
For scenario [discussed in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1203840286200168608)
=> cf: provide option to force reinstall modpack's modloader

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java, src/main/java/me/itzg/helpers/files/Manifests.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1205669805684949022)
Modpack https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/4724273 was patching gregtech at startup
=> curseforge: log files missing from previous modpack install

dev/github.http, src/main/java/me/itzg/helpers/McImageHelper.java, src/main/java/me/itzg/helpers/github/DownloadLatestAssetCommand.java, src/main/java/me/itzg/helpers/github/GithubClient.java, src/main/java/me/itzg/helpers/github/GithubCommands.java, src/main/java/me/itzg/helpers/github/model/Asset.java, src/main/java/me/itzg/helpers/github/model/Release.java, src/test/java/me/itzg/helpers/github/DownloadLatestAssetCommandTest.java, src/test/resources/__files/github/release-with-sources-jar.json
Initially for https://github.com/itzg/docker-minecraft-server/issues/2650
=> Added github subcommand to download latest release asset

src/main/java/me/itzg/helpers/forge/ForgeInstaller.java, src/main/java/me/itzg/helpers/modrinth/Loader.java
Also
- Corrected TYPE written to results env for NeoForge installation
For https://github.com/itzg/docker-minecraft-server/issues/2658
=> modrinth: allow for NeoForge projects

dev/curseforge.http, src/main/java/me/itzg/helpers/curseforge/ModFileRefResolver.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1206745720024211478)
=> cf: support curseforge files that don't delcare any modloader

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/errors/ExceptionHandler.java, src/main/java/me/itzg/helpers/errors/RateLimitException.java, src/main/java/me/itzg/helpers/github/GithubClient.java, src/main/java/me/itzg/helpers/http/FailedRequestException.java, src/main/java/me/itzg/helpers/http/FetchBuilderBase.java, src/test/java/me/itzg/helpers/LatchingExecutionExceptionHandler.java, src/test/java/me/itzg/helpers/github/DownloadLatestAssetCommandTest.java
Related to https://github.com/itzg/docker-minecraft-server/issues/2647
=> github and cf: improve detection and logging of rate limiting

src/main/java/me/itzg/helpers/versions/CompareVersionsCommand.java, src/test/java/me/itzg/helpers/versions/CompareVersionsCommandTest.java
[Reported in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1208989217460322315)
=> version: ensure versions to compare are not blank

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/OverridesFromZipApplier.java, src/main/java/me/itzg/helpers/files/IoStreams.java
=> cf: resolve issue where zip compression scheme prevents manifest file extraction

src/main/java/me/itzg/helpers/curseforge/ModFileRefResolver.java, src/main/java/me/itzg/helpers/files/AntPathMatcher.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java, src/test/java/me/itzg/helpers/modrinth/ModrinthPackInstallerTest.java, src/test/java/me/itzg/helpers/modrinth/ModrinthTestHelpers.java
For https://github.com/itzg/docker-minecraft-server/issues/2700
=> modrinth: support excluding specific overrides

src/main/java/me/itzg/helpers/files/AntPathMatcher.java, src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
For https://github.com/itzg/docker-minecraft-server/issues/2700
=> modrinth: lower logging of overrides

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
=> cf: use www download URL when metadata doesn't contain one

src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
For https://github.com/itzg/docker-minecraft-server/issues/2776
=> modrinth: add option to force include client mods

src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
For https://github.com/itzg/docker-minecraft-server/issues/2776
=> modrinth: fixed force include option

src/main/java/me/itzg/helpers/paper/InstallPaperCommand.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1232998972113551361)
> Hey! I'm getting this error when trying to download the server jar from a custom URL: Version metadata was not available from custom server jar, any ideas? I have it working fine in another server, I'm migrating to a new one but it doesn't work on it, even with the same docker-compose.yml
=> paper: version metadata is optional for custom server jar

src/main/java/me/itzg/helpers/paper/InstallPaperCommand.java
Follow up to #420  since downstream processing needs a valid version
=> paper: fall back to VERSION env var when jar missing metadata

src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java, src/main/java/me/itzg/helpers/curseforge/ModpacksPageUrlParser.java, src/main/java/me/itzg/helpers/paper/PaperDownloadsClient.java, src/test/java/me/itzg/helpers/curseforge/ModpacksPageUrlParserTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2847
=> cf: allow for trailing slash on CF modpack page URL

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/FileHashInvalidException.java, src/main/java/me/itzg/helpers/curseforge/FileHashVerifier.java, src/main/java/me/itzg/helpers/files/ChecksumAlgo.java, src/main/java/me/itzg/helpers/files/Checksums.java, src/test/java/me/itzg/helpers/curseforge/FileHashVerifierTest.java
For https://github.com/itzg/docker-minecraft-server/issues/2865
=> cf: verify hash of downloaded mod files and repair

src/main/java/me/itzg/helpers/paper/InstallPaperCommand.java, src/main/java/me/itzg/helpers/paper/PaperDownloadsClient.java, src/main/java/me/itzg/helpers/paper/model/BuildInfo.java, src/main/java/me/itzg/helpers/paper/model/ReleaseChannel.java, src/main/java/me/itzg/helpers/paper/model/VersionBuilds.java, src/test/java/me/itzg/helpers/paper/PaperDownloadsClientTest.java, src/test/resources/__files/paper/version-builds-response_mix_default_latest.json, src/test/resources/__files/paper/version-builds-response_only_experimental.json
For https://github.com/itzg/docker-minecraft-server/issues/2811
=> paper: consider release channel when selecting version/build

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
For https://github.com/itzg/docker-minecraft-server/issues/2933
=> cf: add support for modpacks that use NeoForge

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/files/Manifests.java
Follow up to https://github.com/itzg/mc-image-helper/pull/449
=> cf: copy files found in downloads that skipped download

src/main/java/me/itzg/helpers/http/FetchBuilderBase.java, src/main/java/me/itzg/helpers/http/OutputToDirectoryFetchBuilder.java
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1261810548161511444)
=> mcopy: support basic auth via URL

src/main/java/me/itzg/helpers/paper/InstallPaperCommand.java
Helps with https://github.com/itzg/docker-minecraft-server/issues/2992
=> paper: suggest other release channel when build not found

src/main/java/me/itzg/helpers/users/ManageUsersCommand.java, src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java
Discovered as part of https://github.com/itzg/docker-minecraft-server/issues/3039
=> users: log warning if attempting to sync from same input file as output

src/main/java/me/itzg/helpers/curseforge/CurseForgeFilesCommand.java, src/test/resources/curseforge/mappings/v1_mods_31043.json
=> cf-files: improve the logging of missing dependencies especially optional ones

dev/modrinth.http, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java, src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java, src/main/java/me/itzg/helpers/modrinth/NoApplicableVersionsException.java, src/main/java/me/itzg/helpers/modrinth/NoFilesAvailableException.java, src/test/java/me/itzg/helpers/modrinth/ModrinthApiClientTest.java, src/test/resources/__files/folia/projects-folia.json, src/test/resources/__files/folia/versions-1-20-6-builds.json, src/test/resources/__files/modrinth/project-version-chunky-fabric-1.21.1.json, src/test/resources/__files/modrinth/project-version-only-beta.json
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1279853370462568519)
Also
- correctly handles extra blank lines in the projects input
=> modrinth: improve logging of non-applicable versions

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
For https://github.com/itzg/docker-minecraft-server/issues/3080
=> auto-cf: support three-part modloader IDs

src/main/java/me/itzg/helpers/McImageHelper.java, src/main/java/me/itzg/helpers/files/TomlQueryCommand.java, src/test/java/me/itzg/helpers/files/TomlQueryCommandTest.java, src/test/resources/velocity.toml
Needed for https://github.com/itzg/docker-mc-proxy/issues/229
=> Add toml-query command

src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java, src/main/java/me/itzg/helpers/fabric/FabricMetaClient.java
Resolving sporadic failures such as 
https://github.com/itzg/docker-minecraft-server/actions/runs/13358120660/job/37303687842?pr=3322#step:6:72
=> fabric: retry download when IO exception

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java
To help debug https://github.com/itzg/docker-minecraft-server/issues/3435
=> cf: when "no matching files found" include retrieved filenames in error

src/main/java/me/itzg/helpers/modrinth/Loader.java
=> Add support for Leaf

src/main/java/me/itzg/helpers/modrinth/Loader.java
Remade to use folia branch, very few plugins should need this but it seems to be the last major server type on modrinth not implemented here, closes #381
=> add modrinth folia support

src/main/java/me/itzg/helpers/modrinth/Loader.java, src/main/java/me/itzg/helpers/paper/InstallPaperCommand.java
Install paper hardcodes type to PAPER, not sure if just removing that is the best idea but if you a recommended way of doing it I can implement that
=> Include Folia in results file

src/main/java/me/itzg/helpers/patch/PatchCommand.java
=> patch: use the new --json-allow-comments in patch set processor

src/main/java/me/itzg/helpers/paper/InstallPaperCommand.java
For #575 
Fixes regression from #570
=> paper: corrected type results output when using url

README.md, src/main/java/me/itzg/helpers/users/ManageUsersCommand.java, src/main/java/me/itzg/helpers/users/model/JavaUser.java, src/main/java/me/itzg/helpers/users/model/UserDef.java, src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java
Solves https://github.com/itzg/docker-minecraft-server/issues/3505
=> user flags + partial offline users in whitelist and ops

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
Part of https://github.com/itzg/mc-image-helper/issues/590
=> cf: also retry file download on Netty ChannelException

README.md, src/main/java/me/itzg/helpers/sync/MulitCopyCommand.java
=> mcopy: provide option to ignore missing remote sources

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java, src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java, src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
Helps with https://github.com/itzg/docker-minecraft-server/issues/3593
=> Limit/config concurrent downloads for CF and Modrinth

src/main/java/me/itzg/helpers/curseforge/ApiKeyHelper.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeFilesCommand.java, src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java, src/main/java/me/itzg/helpers/errors/InvalidApiKeyException.java
Helps troubleshoot https://github.com/itzg/docker-minecraft-server/issues/3591
=> cf: analyze API key when auth failures

src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
[Discovered via Discord chat](https://discord.com/channels/660567679458869252/660569641550217327/1403760984358916106)
=> modrinth: force fabric reinstall when requested for modpacks
