.github/workflows/publish-release.yml
.github/workflows/test.yml
.gitignore
build.gradle
src/main/java/me/itzg/helpers/get/GetCommand.java
src/test/java/me/itzg/helpers/get/GetCommandTest.java

This is all based on what I have found on stack overflow. I have not actually tried any level of integration testing yet.
Source of solution:
https://stackoverflow.com/questions/26552149/how-to-set-x-api-key-in-the-header-of-http-get-request

adding api key to http requests

---

src/main/java/me/itzg/helpers/get/GetCommand.java

Using the default user-agent of Apache HttpClient frequently cause Cloudflare protected domains to reject the request.

Use custom user-agent

---

build.gradle
src/main/java/me/itzg/helpers/assertcmd/FileExists.java
src/test/java/me/itzg/helpers/assertcmd/FileExistsTest.java

Story:
- Need to Assert file exists using wild cards for MC jar files that continuously change.
Acceptance Criteria: 
- Allow the use of globing to verify if files exist: */*.html etc.
Notes:
- Using [ANT](https://ant.apache.org/manual/api/org/apache/tools/ant/DirectoryScanner.html) to use globbing.
- Added Unit tests for new Globing support

Adding support for wild cards in Assert File Exists

---

build.gradle
src/main/java/me/itzg/helpers/assertcmd/FileExists.java
src/test/java/me/itzg/helpers/assertcmd/FileExistsTest.java

When re-running exists tests in itzg/docker-minecraft-server found that relative paths were never getting matched. Stepping through the ant DirectoryScanner code it appears to be quite complicated and archaic.
This change swaps that out with native PathMatcher usage.

fix(assert): adjusted fileExists to support relative paths

---

src/main/java/me/itzg/helpers/get/ContentTypeValidator.java
src/main/java/me/itzg/helpers/get/GetCommand.java
src/main/java/me/itzg/helpers/get/OutputResponseHandler.java
src/main/java/me/itzg/helpers/get/OutputToDirectoryHandler.java
src/main/java/me/itzg/helpers/get/SaveToFileHandler.java
src/test/java/me/itzg/helpers/get/ExistsTest.java
src/test/java/me/itzg/helpers/get/GetCommandTest.java
src/test/java/me/itzg/helpers/get/JsonPathTests.java
src/test/java/me/itzg/helpers/get/MockServerSupport.java
src/test/java/me/itzg/helpers/get/OutputToDirTest.java
src/test/java/me/itzg/helpers/get/OutputToFileTest.java

Will be used to address https://github.com/itzg/docker-minecraft-server/issues/1378

feat(get): validate response content type when using `--accept`

---

src/main/java/me/itzg/helpers/modrinth/model/DependencyType.java

For https://github.com/itzg/docker-minecraft-server/issues/1697

fix(modrinth): missing declaration of embedded dependency type

---

src/main/java/me/itzg/helpers/http/FetchBuilder.java
src/main/java/me/itzg/helpers/http/ObjectListFetchBuilder.java
src/main/java/me/itzg/helpers/http/ObjectListMapperHandler.java
src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java

Additional fix for https://github.com/itzg/docker-minecraft-server/issues/1697

fix(modrinth): correctly retrieve specific dependency version info

---

src/main/java/me/itzg/helpers/get/GetCommand.java
src/test/java/me/itzg/helpers/get/GetCommandTest.java
src/test/java/me/itzg/helpers/get/MockServerSupport.java

feat(get): add support for user info in URL

---

src/main/java/me/itzg/helpers/McImageHelper.java
src/main/java/me/itzg/helpers/errors/ExceptionHandler.java
src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
src/main/java/me/itzg/helpers/sync/InterpolateCommand.java

Also
- sync: throw exception from sync
- log stack trace with execution exception
- forge: log stack trace when file deletion fails
As noted [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1054724491244220466), one would think `DEBUG` from the usual startup debugging would work. In #38 I switched the var from DEBUG to DEBUG_HELPER since the output was interfering with script operations using output of helper. In #42 I changed debug logs to go to stderr and should have added back `DEBUG `support.

Accept DEBUG env var for enabling debugs

---

src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java

Observed with
```
--exclude-include-file=https://raw.githubusercontent.com/itzg/docker-minecraft-server/master/files/cf-exclude-include.json
```

curseforge: allow for any content type for exclude-include download

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java

curseforge: support modpack zip when files before directories

---

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java

closes #49 
Using colon to declare specific version id of a Modrinth's mod. 
Also, I'm not sure if this is the best solution for this; I checked #74 and there is a suggestion to use ``mod#version``.

Support specific version ID declaration for Modrinth

---

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java

Allow the project version type to be declared using the same method as the version id.
To be honest, this code looks like spaghetti so I will mark this a draft PR.

Allow per project version type declaration

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/test/java/me/itzg/helpers/curseforge/CurseForgeInstallerTest.java

For https://github.com/itzg/docker-minecraft-server/issues/1946

curseforge: handle modpack slug that clashes with mod slug

---

src/main/java/me/itzg/helpers/http/FetchBuilderBase.java

http: pre-encode URIs to fully handle unicode in path

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
src/main/java/me/itzg/helpers/http/Fetch.java
src/main/java/me/itzg/helpers/http/FetchBuilderBase.java
src/main/java/me/itzg/helpers/http/SharedFetch.java
src/main/java/me/itzg/helpers/http/SharedFetchArgs.java
src/test/java/me/itzg/helpers/env/InterpolatorTest.java

Discussed [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1074203479188443207)

http: configurable timeout for response and TLS handshake

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java

For https://github.com/itzg/docker-minecraft-server/issues/1972

curseforge: ensure modpack-file listing is not out-dated

---

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java

It appears that [the API docs](https://docs.modrinth.com/api-spec/#tag/versions/operation/getProjectVersions) are now incorrect in stating the query parameters should be quoted arrays. Instead the API now seems to only return items when using regular values.
For https://github.com/itzg/docker-minecraft-server/issues/1973

modrinth: adapt version lookup API

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
src/main/java/me/itzg/helpers/files/BaseManifest.java
src/main/java/me/itzg/helpers/files/Manifests.java
src/main/java/me/itzg/helpers/http/SpecificFileFetchBuilder.java
src/main/java/me/itzg/helpers/modrinth/LegacyModrinthManifest.java
src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
src/main/java/me/itzg/helpers/modrinth/ModrinthManifest.java

Discussed at https://github.com/itzg/docker-minecraft-server/issues/1973#issuecomment-1455182501

modrinth: expand downloaded zip files

---

src/main/java/me/itzg/helpers/McImageHelper.java
src/main/java/me/itzg/helpers/errors/ExceptionHandler.java
src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
src/main/java/me/itzg/helpers/forge/InstallForgeCommand.java

forge: allow 'latest' minecraft version and handle missing version

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/model/CurseForgeResponse.java
src/main/java/me/itzg/helpers/http/FailedRequestException.java
src/main/java/me/itzg/helpers/http/FetchBuilderBase.java
src/main/java/me/itzg/helpers/http/ObjectFetchBuilder.java
src/main/java/me/itzg/helpers/http/OutputToDirectoryFetchBuilder.java
src/main/java/me/itzg/helpers/http/SpecificFileFetchBuilder.java

Also properly handles and reports a file that isn't present for the requested modpack project.

cf: report missing manifest as invalid parameter

---

src/main/java/me/itzg/helpers/forge/ForgeInstaller.java

Resolves #174 
cc @kevinkjt2000

forge: support 1.7.x install_profile.json

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java

Reported in https://github.com/itzg/docker-minecraft-server/issues/2045

curseforge: check file downloadUrl for availability

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/http/FetchBuilderBase.java

Also:
curseforge handle null modpack downloadUrl
Originally reported in https://github.com/itzg/docker-minecraft-server/issues/2007

http: redact sensitive headers from debug logs

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeManifest.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
src/main/java/me/itzg/helpers/curseforge/ModPackResults.java

Discovered from https://github.com/itzg/docker-minecraft-server/issues/2056

cf: handle modpacks and mods where authors don't allow distribution

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java

cf: cleanup remaining parallelism that's redundant

---

src/main/java/me/itzg/helpers/patch/Json5FileFormat.java
src/main/java/me/itzg/helpers/patch/PatchSetProcessor.java
src/test/java/me/itzg/helpers/patch/PatchSetProcessorTest.java
src/test/resources/patch/expected-setInJson5.json5
src/test/resources/patch/testing.json5

JSON5 Support

---

src/main/java/me/itzg/helpers/http/SharedFetchArgs.java
src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java
src/main/java/me/itzg/helpers/modrinth/Loader.java
src/main/java/me/itzg/helpers/modrinth/ModpackLoader.java

Includes things left out of #217

modrinth: adjust modpack options

---

build.gradle
src/main/java/me/itzg/helpers/McImageHelper.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java
src/main/java/me/itzg/helpers/errors/Validators.java
src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
src/main/java/me/itzg/helpers/http/OutputToDirectoryFetchBuilder.java
src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java
src/main/java/me/itzg/helpers/mvn/MavenRepoApi.java
src/main/java/me/itzg/helpers/patch/PatchSetProcessor.java
src/main/java/me/itzg/helpers/purpur/InstallPurpurCommand.java
src/main/java/me/itzg/helpers/quilt/InstallQuiltCommand.java
src/main/java/me/itzg/helpers/quilt/QuiltInstaller.java
src/main/java/me/itzg/helpers/sync/MulitCopyCommand.java
src/main/java/me/itzg/helpers/vanillatweaks/VanillaTweaksCommand.java
src/main/java/me/itzg/helpers/versions/MinecraftVersionsApi.java
src/main/java/me/itzg/helpers/versions/ResolveMinecraftVersionCommand.java
src/main/java/me/itzg/helpers/versions/VersionManifestV2.java

Also
- added resolve-minecraft-version subcommand

quilt: support custom URL of installer

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java

A new info log will be shown for exclusions:
```
[mc-image-helper] 11:07:49.124 INFO  : Excluding mod file 'AmbientSounds 5' (ambientsounds) due to configuration
```

cf: allow includes to override excludes

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
src/main/java/me/itzg/helpers/curseforge/MissingModsException.java
src/main/java/me/itzg/helpers/files/TabularOutput.java

Inspired by [discussion in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1128444887063330836)

cf: fail if any manual mod downloads are needed

---

dev/.gitignore
dev/curseforge.http
dev/purpur.http
src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
src/main/java/me/itzg/helpers/curseforge/model/ModLoaderType.java

For https://github.com/itzg/docker-minecraft-server/issues/2307

cf: added support for ModLoaderType=6 for NeoForge

---

src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java

Was missing propagation of command field to the API fetcher.

modrinth: option to ignore missing files from modpack update check

---

src/main/java/me/itzg/helpers/curseforge/ModFileRefResolver.java

Slugs can contain digits, e.g. [this mod](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib), although I assume the first character can't be a digit

Match numbers in curseforge slugs

---

src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
src/test/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommandTest.java
src/test/java/me/itzg/helpers/modrinth/ModrinthPackInstallerTest.java
src/test/java/me/itzg/helpers/modrinth/ModrinthTestHelpers.java

[This modpack's index](https://cdn-raw.modrinth.com/data/vwgtbO0y/versions/pcBAoLzK/The%20Pixelmon%20Modpack%209.2.3.mrpack) used backslashes in the file paths:
```json
{
"formatVersion": 1,
"game": "minecraft",
"versionId": "Pixelmon-1.20.1-9.2.3",
"name": "Pixelmon Mod",
"summary": "You probably all know Pokemon. Pixelmon is basically the same only it is on a Minecraft server! You can catch pokemon, battle trainers, compete with each other and against other pokemon, earn gym badges, upgrade your pokemons with attacks and trade with each other. \r\n\r\nThis pack requires 800mb to 2gb of RAM for optimal performance. \r\nJava 17 - 64 bit is required. \r\n\r\nWebsite:\r\nhttps://pixelmonmod.com/\r\nhttps://www.reforged.gg/",
"files": [
{
"path": "mods\\Pixelmon-1.20.1-9.2.3-universal.jar", …
```

modrinth: sanitize modpack file's path

---

src/main/java/me/itzg/helpers/http/SharedFetch.java
src/main/java/me/itzg/helpers/http/SharedFetchArgs.java

Mentioned a few times in Discord, [such as this one](https://discord.com/channels/660567679458869252/660569755320844308/1175095138247262249).
Also increased from Netty's default of 45 seconds to 2 minutes.

http: allow configurable connection pool acquire timeout

---

src/main/java/me/itzg/helpers/http/SharedFetch.java

Similar to https://github.com/itzg/mc-image-helper/pull/20
This change allows the container to use my proxy server when downloading fabric server if I add (not sure which of these is used by the tool, but IIRC both are needed):
```yaml
environment:
HTTP_PROXY: "http://10.0.16.7:3128"
JAVA_TOOL_OPTIONS: "-Dhttps.proxyHost=10.0.16.7 -Dhttps.proxyPort=3128 -XX:+PerfDisableSharedMem"
```

Use proxyWithSystemProperties in SharedFetch

---

.run/modrinth-modpack (slug).run.xml
dev/modrinth.http
src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java
src/main/java/me/itzg/helpers/modrinth/ModpackLoader.java
src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
src/main/java/me/itzg/helpers/modrinth/model/DependencyId.java
src/test/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommandTest.java
src/test/java/me/itzg/helpers/modrinth/ModrinthPackInstallerTest.java
src/test/java/me/itzg/helpers/modrinth/ModrinthTestHelpers.java

For https://github.com/itzg/docker-minecraft-server/issues/2640

modrinth: add support for NeoForge as a modpack's modloader

---

src/main/java/me/itzg/helpers/users/ManageUsersCommand.java
src/main/java/me/itzg/helpers/users/MojangUserApi.java
src/main/java/me/itzg/helpers/users/PlayerdbUserApi.java
src/main/java/me/itzg/helpers/users/UserApi.java
src/main/java/me/itzg/helpers/users/UserApiProvider.java
src/main/java/me/itzg/helpers/users/UuidQuirks.java
src/main/java/me/itzg/helpers/users/ext/PlayerdbPlayer.java
src/main/java/me/itzg/helpers/users/ext/PlayerdbResponse.java
src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java

Was starting to see 429's from Mojang's user lookup API. With this change the provider can be switched via `USER_API_PROVIDER` env var.

users: add support for playerdb lookup and use by default

---

src/main/java/me/itzg/helpers/http/FilenameExtractor.java
src/test/java/me/itzg/helpers/http/OutputToDirectoryFetchBuilderTest.java

This PR modifies the method `filenameFromContentDisposition` in `FilenameExtractor` to return null instead of throwing an exception if a filename cannot be extracted from the header.
This allows a filename to still be determined by response path if not correctly determined by the header.

Fix exception in FilenameExtractor.filenameFromContentDisposition

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeFilesCommand.java
src/main/java/me/itzg/helpers/curseforge/ModFileRefResolver.java
src/main/java/me/itzg/helpers/files/Manifests.java
src/test/java/me/itzg/helpers/curseforge/CurseForgeFilesCommandTest.java

[Reported in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1233829899928862850)
After an container restart I'm hit with this issue:
```
[mc-image-helper] 19:02:26.734 INFO  : Fabric launcher for minecraft 1.20.1 loader 0.15.10 is already available
[mc-image-helper] 19:02:28.217 INFO  : Downloading /data/mods/Structory_1.20.1_v1.3.2.jar from https://mediafilez.forgecdn.net/files/4630/983/Structory_1.20.1_v1.3.2.jar
[mc-image-helper] 19:02:29.234 ERROR : 'curseforge-files' command failed. Version is 1.38.5
java.lang.IllegalStateException: Duplicate key ModFileIds(modId=667389, fileId=4802504) (attempted merging values CurseForgeFilesManifest.FileEntry(ids=ModFileIds(modId=667389, fileId=4802504), filePath=mods/goblintraders-fabric-1.20.1-1.9.3.jar) and …
```

cf-files: correctly handle duplicate file refs

---

src/main/java/me/itzg/helpers/paper/InstallPaperCommand.java

Reverts #422 and #420
The custom server jar that prompted the original changes had an extraneous top level folder

paper: restore requirement of version.json metadata

---

src/main/java/me/itzg/helpers/forge/NeoForgeInstallerResolver.java
src/test/java/me/itzg/helpers/forge/NeoForgeInstallerResolverTest.java
src/test/resources/__files/forge/neoforged-neoforge-maven-metadata.xml

For https://github.com/itzg/docker-minecraft-server/issues/2934

neoforge: correctly handle versioning that drops the ".0"

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/FileHashVerifier.java

For https://github.com/itzg/docker-minecraft-server/issues/2983

cf: check downloads repo before attempting download of mod in modpack

---

src/main/java/me/itzg/helpers/http/FetchBuilderBase.java

http: avoid logging user info from URLs

---

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java

Was observed with https://modrinth.com/plugin/geyserextras/version/1.21.0-v1.1.3
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1263129186181189756)

modrinth: re-download Modrinth projects based on modified time rather than filename existence

---

src/main/java/me/itzg/helpers/modrinth/Loader.java
src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java
src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
src/main/java/me/itzg/helpers/modrinth/ProjectRef.java
src/main/java/me/itzg/helpers/modrinth/model/Constants.java
src/main/java/me/itzg/helpers/modrinth/model/Version.java
src/test/java/me/itzg/helpers/modrinth/ModrinthCommandTest.java
src/test/java/me/itzg/helpers/modrinth/ProjectRefTest.java

For https://github.com/itzg/docker-minecraft-server/issues/3088

modrinth: support datapack retrieval

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeFilesCommand.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
src/main/java/me/itzg/helpers/files/ApiCaching.java
src/main/java/me/itzg/helpers/files/ApiCachingImpl.java
src/main/java/me/itzg/helpers/files/CacheIndex.java
src/main/java/me/itzg/helpers/files/DisabledApiCaching.java
src/test/java/me/itzg/helpers/curseforge/CurseForgeApiClientTest.java
src/test/java/me/itzg/helpers/curseforge/ModFileRefResolverTest.java
src/test/resources/curseforge/mappings/v1_mods_238222.json
src/test/resources/curseforge/mappings/v1_mods_31054.json
src/test/resources/curseforge/mappings/v1_mods_667389.json

For https://github.com/itzg/docker-minecraft-server/discussions/3101 and probably other discussions

curseforge: cache get mod info and file API calls to disk

---

src/main/java/me/itzg/helpers/McImageHelper.java
src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
src/main/java/me/itzg/helpers/modrinth/model/ProjectType.java
src/main/java/me/itzg/helpers/singles/TestLoggingCommand.java
src/test/java/me/itzg/helpers/modrinth/ModrinthCommandTest.java

For https://github.com/itzg/docker-minecraft-server/issues/3140
Noticed with https://modrinth.com/datapack/animated-doors since it depends on a resource pack https://modrinth.com/resourcepack/animated-door/versions

modrinth: more info in error when dependency has no applicable files

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeFilesCommand.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/ModFileRefResolver.java
src/main/java/me/itzg/helpers/curseforge/OutputPaths.java
src/main/java/me/itzg/helpers/curseforge/OutputSubdirResolver.java
src/main/java/me/itzg/helpers/files/ReactiveFileUtils.java
src/main/java/me/itzg/helpers/vanillatweaks/VanillaTweaksCommand.java

For https://github.com/itzg/docker-minecraft-server/issues/3150

cf: use fallback URL for curseforge files like modpack files

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java

For https://github.com/itzg/docker-minecraft-server/issues/3236

cf: gracefully handle invalid modpack manifest file

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java
src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/model/package-info.java

For https://github.com/itzg/docker-minecraft-server/issues/3252

cf: qualify mapping of excluded slug to mod IDs

---

src/main/java/me/itzg/helpers/McImageHelper.java
src/main/java/me/itzg/helpers/cache/ApiCachingImpl.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java

For https://github.com/itzg/docker-minecraft-server/issues/3255

cf: handle spaces around commas in exclude/include args

---

src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
src/main/java/me/itzg/helpers/forge/ProvidedInstallerResolver.java
src/main/java/me/itzg/helpers/forge/VersionPair.java
src/test/java/me/itzg/helpers/forge/ProvidedInstallerResolverTest.java
src/test/resources/forge/version-cleanroom.json
src/test/resources/forge/version-forge-1.12.2.json
src/test/resources/forge/version-forge-1.20.2.json

For https://github.com/itzg/docker-minecraft-server/issues/3274

forge: support CleanroomMC installer

---

src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
src/main/java/me/itzg/helpers/fabric/FabricMetaClient.java

Handle build test failures [like](https://github.com/itzg/docker-minecraft-server/actions/runs/13102417838/job/36552311263?pr=3292)
```
:::::::::::: LOGS ::::::::::::::::
Network modrinth_default  Creating
Network modrinth_default  Created
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Feb  2 21:16 /data'
[init] Resolving type given FABRIC
[mc-image-helper] 21:16:16.710 ERROR : 'install-fabric-loader' command failed. Version is 1.40.12
reactor.core.Exceptions$ReactiveException: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response
at reactor.core.Exceptions.propagate(Exceptions.java:410)
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscr …
```

fabric: retry download when IO exception

---

src/main/java/me/itzg/helpers/fabric/FabricMetaClient.java
src/test/java/me/itzg/helpers/fabric/FabricLauncherInstallerTest.java

For https://github.com/itzg/docker-minecraft-server/issues/3331

fabric: skip fabricmc API call when matching version installed

---

build.gradle

Issue: #385 
Saw the open issue and thought it would be low hanging fruit, gradle toolchain setup to match the current java version used by github action. 
Also removed a duplicate source compatibility setting from build.gradle

Fix #385 with gradle toolchain

---

src/main/java/me/itzg/helpers/sync/Sync.java
src/main/java/me/itzg/helpers/sync/SyncAndInterpolate.java
src/main/java/me/itzg/helpers/sync/SynchronizingFileVisitor.java
src/test/java/me/itzg/helpers/sync/SyncAndInterpolateTest.java

For https://github.com/itzg/docker-minecraft-server/issues/3367

sync: allow multiple source directories

---

README.md
src/main/java/me/itzg/helpers/sync/SynchronizingFileVisitor.java
src/test/java/me/itzg/helpers/sync/SyncAndInterpolateTest.java

sync: skip missing source directories

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
src/main/java/me/itzg/helpers/fabric/InstallFabricLoaderCommand.java
src/main/java/me/itzg/helpers/http/SharedFetchArgs.java
src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java
src/test/java/me/itzg/helpers/fabric/FabricLauncherInstallerTest.java

[From Discord](https://discord.com/channels/660567679458869252/660567682751528981/1360484392916484208)
Also
- default `FETCH_CONNECTION_POOL_MAX_IDLE_TIMEOUT` to 15s referring to https://projectreactor.io/docs/netty/release/reference/faq.html#faq.connection-closed
```
[init] Resolving type given FABRIC
[mc-image-helper] 05:14:00.972 ERROR : 'install-fabric-loader' command failed. Version is 1.41.6
reactor.core.Exceptions$RetryExhaustedException: Retries exhausted: 5/5
at reactor.core.Exceptions.retryExhausted(Exceptions.java:308)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
*__checkpoint ⇢ downloadLauncher
*__checkpoint ⇢ downloadResolvedLauncher
Original Stack Trace:
at …
```

fabric: accept shared fetch/netty arguments

---

src/main/java/me/itzg/helpers/http/FetchBuilderBase.java
src/main/java/me/itzg/helpers/http/OutputToDirectoryFetchBuilder.java

Closes #549 
This is a new approach to handling failing HEAD requests, derived from the discussion in #550 
Basically, this PR re-orders the conditional failing of a request if the HEAD fetching did not work as expected. For example, presigned S3 URLs do not support HEAD requests and respond with a 403.
Also, `isHeadUnsupportedResponse` now returns true as well when the HEAD response was a 403. (to gracefully handle the before mentioned).
Testing with the following URL (expiring on May 5th) now works as expected (also determining the right filename):
<details><summary>Details</summary>
<p>
`https://nbg1.your-objectstorage.com/ziffer-artifacts-staging/builds/4e8f7980-3955-48c4-9ff9-9a8dbedcbf41/test-plugin-1.0-SNAPSHOT.jar?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=6OL4X4U2SMEH6AKWA7 …

Check for unsupported HEAD before failing request

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeApiClient.java

Trying to better diagnose build failures like https://github.com/itzg/docker-minecraft-server/actions/runs/14755417954/attempts/2

cf: include more detail with "No matching files found for mod" error

---

README.md
src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/patch/JsonFileFormat.java
src/main/java/me/itzg/helpers/patch/PatchCommand.java
src/main/java/me/itzg/helpers/patch/PatchSetProcessor.java
src/test/java/me/itzg/helpers/patch/PatchSetProcessorTest.java
src/test/resources/patch/testing-with-comment.json

patch: allow option to allow comments in json files

---

src/main/java/me/itzg/helpers/users/ManageUsersCommand.java
src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java

Offline UUID implementation, used if `manage-users` receives `--offline` flag

feat(users): offline UUD generation support

---

src/main/java/me/itzg/helpers/modrinth/ModrinthCommand.java
src/test/java/me/itzg/helpers/modrinth/ModrinthCommandTest.java

Uses the same syntax as Curseforge: `@/path/to/modrinth-mods.txt`. Added tests to make sure it is working as expected. I tried to follow how it was done for Curseforge as closely as possible to keep things consistent. I will make a separate PR to update the docs at itzg/docker-minecraft-server/docs/mods-and-plugins/modrinth.md
docs PR: https://github.com/itzg/docker-minecraft-server/pull/3506

Add Modrinth project files support

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java
src/main/java/me/itzg/helpers/forge/ForgeInstallerResolver.java
src/main/java/me/itzg/helpers/forge/ForgeUrlArgs.java
src/main/java/me/itzg/helpers/forge/InstallForgeCommand.java
src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java
src/main/java/me/itzg/helpers/modrinth/ModrinthPackInstaller.java

Handles future cases like #607

forge|cf|modrinth: Forge promotions and maven URLs are configurable

---

src/main/java/me/itzg/helpers/fabric/FabricMetaClient.java

fabric: properly retry download when fabric installer is invalid

---

.run/modrinth-modpack (slug).run.xml
src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/fabric/FabricMetaClient.java
src/main/java/me/itzg/helpers/files/ByteBufQueue.java
src/main/java/me/itzg/helpers/files/ReactiveFileUtils.java
src/main/java/me/itzg/helpers/http/SharedFetch.java
src/main/java/me/itzg/helpers/http/SharedFetchArgs.java

Delegate file writing via queue and option to disable HTTP/2

---

src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java
src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
src/main/java/me/itzg/helpers/files/ReactiveFileUtils.java
src/main/java/me/itzg/helpers/http/SharedFetchArgs.java

Otherwise it'll potentially skip the download seeing that the file is present

cf: remove failed file downloads

---

src/main/java/me/itzg/helpers/users/ManageUsersCommand.java
src/test/java/me/itzg/helpers/users/ManageUsersCommandTest.java

users: wrap JSON parsing error of existing ops/whitelist
